title: Zach Dyer Design
email: zach.dyer@zachdyerdesign.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Zach Dyer Design, a passionate and skilled software development team with a knack for creating sleek, modern websites that prioritize both aesthetics and functionality.
  We specialize in building lightweight, secure websites that load quickly and perform exceptionally well in search engine rankings. We have a strong understanding of the latest technologies and trends in web development, and are dedicated to staying up-to-date on the latest best practices in order to deliver the best possible product for our clients.
  Whether you need a new website built from scratch, or an existing site in need of an update, Zach Dyer Design has the skills and expertise to bring your vision to life. So if you're looking for a tech-savvy professional who can create stunning, high-performing websites that stand out in a crowded online landscape, look no further than Zach Dyer Design.
tagline: Transform your online presence with beautiful, fast, and secure websites crafted by Zach Dyer Design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zachdyerdesign.com" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 3
paginate_path: "/blog/page:1"
pagination_layout: blog-home
tier: premium

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
