# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zach Dyer Design
email: zach.dyer@zachdyerdesign.com
description: Zach Dyer Design LLC is a full service web design company located in Ozark, Missouri in the Carl Hefner Business Enterprise. We provide web design, branding design, web programming, domain and hosting services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zachdyerdesign.com" # the base hostname & protocol for your site
twitter_username: zachdyer
github_username:  zachdyerdesign
linkedin_profile: zach-dyer-83389821
facebook: Zach-Dyer-Design-175044499220188
telephone: +1 417 501 5670
address: 1471 W South St, Ozark, MO 65721

# Build settings
markdown: kramdown
